### ISSUE TITLE
LogicException: Attempted to set 'post_date' while a save was pending without forceSet

### ISSUE THREAD

**Issue by zastavra** [ticktackk/ChangeContentOwnerForXF2#26]
LogicException: Attempted to set 'post_date' while a save was pending without forceSet src/XF/Mvc/Entity/Entity.php:575

**Stack trace**

> #0 src/XF/Mvc/Entity/Entity.php(548): XF\Mvc\Entity\Entity->set('post_date', 1233514800)
#1 src/addons/TickTackk/ChangeContentOwner/XF/Service/Post/OwnerChanger.php(76): XF\Mvc\Entity\Entity->__set('post_date', 1233514800)
#2 src/addons/TickTackk/ChangeContentOwner/Service/Content/AbstractOwnerChanger.php(714): TickTackk\ChangeContentOwner\XF\Service\Post\OwnerChanger->changeContentDate(Object(SV\ModeratorEssentials\XF\Entity\Post), 1233514800)
#3 src/XF/Service/ValidateAndSavableTrait.php(40): TickTackk\ChangeContentOwner\Service\Content\AbstractOwnerChanger->_save()
#4 src/addons/TickTackk/ChangeContentOwner/Service/Content/EditorTrait.php(114): TickTackk\ChangeContentOwner\Service\Content\AbstractOwnerChanger->save()
#5 src/XF/Service/ValidateAndSavableTrait.php(40): TickTackk\ChangeContentOwner\XF\Service\Post\Editor->_save()
#6 src/XF/Pub/Controller/Post.php(135): XF\Service\Post\Editor->save()
#7 src/addons/TickTackk/ChangeContentOwner/XF/Pub/Controller/Post.php(66): XF\Pub\Controller\Post->actionEdit(Object(XF\Mvc\ParameterBag))
#8 src/addons/EWR/Porta/Pub/Controller/Post.php(39): TickTackk\ChangeContentOwner\XF\Pub\Controller\Post->actionEdit(Object(XF\Mvc\ParameterBag))
#9 src/XF/Mvc/Dispatcher.php(321): EWR\Porta\Pub\Controller\Post->actionEdit(Object(XF\Mvc\ParameterBag))
#10 src/XF/Mvc/Dispatcher.php(244): XF\Mvc\Dispatcher->dispatchClass('XF:Post', 'Edit', Object(XF\Mvc\RouteMatch), Object(EWR\Porta\Pub\Controller\Post), NULL)
#11 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(EWR\Porta\Pub\Controller\Post), NULL)
#12 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#13 src/XF/App.php(2178): XF\Mvc\Dispatcher->run()
#14 src/XF.php(390): XF\App->run()
#15 index.php(20): XF::runApp('XF\\Pub\\App')
#16 {main}

**Comment by ticktackk** [comment]
Fixed in RC3 https://github.com/ticktackk/ChangeContentOwnerForXF2/releases/tag/2000053
