### ISSUE TITLE
News feed event date does not update for the expected action

### ISSUE THREAD

**Issue by ticktackk** [ticktackk/ChangeContentOwnerForXF2#44]

**Comment by GH-Rake** [comment]
This latest update causes an error when upgrading

`TypeError: Argument 2 passed to TickTackk\ChangeContentOwner\Job\Upgrade\RebuildNewsFeedEntryEventDate::applyReactionOrLikeContentConditions() must be an instance of XF\Mvc\Entity\Entity, null given, called in 
/FULL_PATH_REMOVED/public/src/addons/TickTackk/ChangeContentOwner/Job/Upgrade/RebuildNewsFeedEntryEventDate.php on line 130 in src/addons/TickTackk/ChangeContentOwner/Job/Upgrade/RebuildNewsFeedEntryEventDate.php at line 198
TickTackk\ChangeContentOwner\Job\Upgrade\RebuildNewsFeedEntryEventDate->applyReactionOrLikeContentConditions() in src/addons/TickTackk/ChangeContentOwner/Job/Upgrade/RebuildNewsFeedEntryEventDate.php at line 130
TickTackk\ChangeContentOwner\Job\Upgrade\RebuildNewsFeedEntryEventDate->rebuildReactionOrLike() in src/addons/TickTackk/ChangeContentOwner/Job/Upgrade/RebuildNewsFeedEntryEventDate.php at line 156
TickTackk\ChangeContentOwner\Job\Upgrade\RebuildNewsFeedEntryEventDate->rebuildEventDateReaction() in src/addons/TickTackk/ChangeContentOwner/Job/Upgrade/RebuildNewsFeedEntryEventDate.php at line 73
TickTackk\ChangeContentOwner\Job\Upgrade\RebuildNewsFeedEntryEventDate->rebuildById() in src/XF/Job/AbstractRebuildJob.php at line 47
XF\Job\AbstractRebuildJob->run() in src/XF/Job/Manager.php at line 253
XF\Job\Manager->runJobInternal() in src/XF/Job/Manager.php at line 195
XF\Job\Manager->runJobEntry() in src/XF/Job/Manager.php at line 111
XF\Job\Manager->runByIds() in src/XF/Admin/Controller/Tools.php at line 120
XF\Admin\Controller\Tools->actionRunJob() in src/XF/Mvc/Dispatcher.php at line 350
XF\Mvc\Dispatcher->dispatchClass() in src/XF/Mvc/Dispatcher.php at line 257
XF\Mvc\Dispatcher->dispatchFromMatch() in src/XF/Mvc/Dispatcher.php at line 113
XF\Mvc\Dispatcher->dispatchLoop() in src/XF/Mvc/Dispatcher.php at line 55
XF\Mvc\Dispatcher->run() in src/XF/App.php at line 2184
XF\App->run() in src/XF.php at line 391
XF::runApp() in admin.php at line 13`

**Comment by ticktackk** [comment]
@GH-Rake I have updated the add-on archive to include the fix. Please try again.

**Comment by GH-Rake** [comment]
Worked great, thank you, error is gone now!
