### ISSUE TITLE
There are manual rebuild jobs awaiting completion. Continue running them.

### ISSUE THREAD

**Issue by bigbrain911** [ticktackk/ChangeContentOwnerForXF2#68]
Server error log
LogicException: Content type graph must define an 'entity' value src/XF/App.php:2568
Generated by: ZLOY May 3, 2020 at 1:24 PM
Stack trace
#0 src/addons/TickTackk/ChangeContentOwner/Job/Upgrade/RebuildAttachmentOwner.php(42): XF\App->getContentTypeEntity('graph')
#1 src/XF/Job/AbstractRebuildJob.php(30): TickTackk\ChangeContentOwner\Job\Upgrade\RebuildAttachmentOwner->getNextIds(0, 100)
#2 src/XF/Job/Manager.php(253): XF\Job\AbstractRebuildJob->run(G)
#3 src/XF/Job/Manager.php(195): XF\Job\Manager->runJobInternal(Array, G)
#4 src/XF/Job/Manager.php(79): XF\Job\Manager->runJobEntry(Array, G)
#5 src/XF/Admin/Controller/Tools.php(139): XF\Job\Manager->runQueue(true, 8)
#6 src/XF/Mvc/Dispatcher.php(350): XF\Admin\Controller\Tools->actionRunJob(Object(XF\Mvc\ParameterBag))
#7 src/XF/Mvc/Dispatcher.php(257): XF\Mvc\Dispatcher->dispatchClass('XF:Tools', 'RunJob', Object(XF\Mvc\RouteMatch), Object(XF\Admin\Controller\Tools), NULL)
#8 src/XF/Mvc/Dispatcher.php(113): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(XF\Admin\Controller\Tools), NULL)
#9 src/XF/Mvc/Dispatcher.php(55): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#10 src/XF/App.php(2184): XF\Mvc\Dispatcher->run()
#11 src/XF.php(391): XF\App->run()
#12 admin.php(13): XF::runApp('XF\\Admin\\App')
#13 {main}
Request state
array(4) {
  ["url"] => string(24) "/admin.php?tools/run-job"
  ["referrer"] => string(45) "/admin.php?tools/run-job"
  ["_GET"] => array(1) {
    ["tools/run-job"] => string(0) ""
  }
  ["_POST"] => array(3) {
    ["_xfRedirect"] => string(10) "/admin.php"
    ["_xfToken"] => string(8) "********"
    ["only_ids"] => string(0) ""
  }
}

**Comment by ticktackk** [comment]
Re-download the most recent files and upload them.
