### ISSUE TITLE
Copied a thread, changed date, then changed time

### ISSUE THREAD

**Issue by bigfooty** [ticktackk/ChangeContentOwnerForXF2#70]
I copied a thread, then changed the date.
I realised the time was 8 hours in the future, so I changed the time to 30 minutes in the past.

Got this error:

Oops! We ran into some problems.
Error: Call to undefined method SV\UserEssentials\XF\Service\Thread\Editor::getNewTimestamp() in src/addons/TickTackk/ChangeContentOwner/ControllerPlugin/Content.php at line 200
TickTackk\ChangeContentOwner\ControllerPlugin\Content->setNewOwnerDateTimeAndInterval() in src/addons/TickTackk/ChangeContentOwner/ControllerPlugin/Content.php at line 108
TickTackk\ChangeContentOwner\ControllerPlugin\Content->extendEditorService() in src/addons/TickTackk/ChangeContentOwner/XF/Pub/Controller/Thread.php at line 71
TickTackk\ChangeContentOwner\XF\Pub\Controller\Thread->setupThreadEdit() in src/addons/SV/StickyAnyPost/XF/Pub/Controller/Thread.php at line 14
SV\StickyAnyPost\XF\Pub\Controller\Thread->setupThreadEdit() in src/addons/SV/StickyThreadOrder/XF/Pub/Controller/Thread.php at line 15
SV\StickyThreadOrder\XF\Pub\Controller\Thread->setupThreadEdit() in src/addons/SV/UserEssentials/XF/Pub/Controller/Thread.php at line 81
SV\UserEssentials\XF\Pub\Controller\Thread->setupThreadEdit() in src/XF/Pub/Controller/Thread.php at line 672
XF\Pub\Controller\Thread->actionEdit() in src/addons/TickTackk/ChangeContentOwner/XF/Pub/Controller/Thread.php at line 50
TickTackk\ChangeContentOwner\XF\Pub\Controller\Thread->actionEdit() in src/XF/Mvc/Dispatcher.php at line 350
XF\Mvc\Dispatcher->dispatchClass() in src/XF/Mvc/Dispatcher.php at line 261
XF\Mvc\Dispatcher->dispatchFromMatch() in src/XF/Mvc/Dispatcher.php at line 113
XF\Mvc\Dispatcher->dispatchLoop() in src/XF/Mvc/Dispatcher.php at line 55
XF\Mvc\Dispatcher->run() in src/XF/App.php at line 2190
XF\App->run() in src/XF.php at line 391
XF::runApp() in index.php at line 20

**Comment by ticktackk** [comment]
What version of User Essentials are you running?

**Comment by bigfooty** [comment]
User Essentials 3.7.0

**Comment by bigfooty** [comment]
BUT - we are a version or two behind with your addon.

**Comment by bigfooty** [comment]
Works after latest update. Cheers.
