### ISSUE TITLE
Threads / Posts should be hidden until the Scheduled is cleared

### ISSUE THREAD

**Issue by jiraniba** [ticktackk/ChangeContentOwnerForXF2#71]
I love so much this addon but I can see a major issue that except logic.

When setting scheduled time, the thread or post should be hidden to others until the Scheduled is cleared. 

You can follow [BS] Scheduled posting, that addon has this feature. 

[BS] Scheduled posting have:

View scheduled publications: https://i.imgur.com/GRm5Tt2.png (This way, the thread/post can view who have permission)
 
This is very important due to the users confused why thread/posts dates are showing the future date. Even if the post date is changed to a future date, nobody can reply that thread. This means thread goes stop work until the Scheduled is cleared.

**Comment by ticktackk** [comment]
The add-on is only used for changing owner and/or date of content. This is not a replacement for scheduled content.

**Comment by jiraniba** [comment]
I understand but its make confused to peoples really, please review by post again.

**Comment by smallersign** [comment]
yes, I face the same issue and I just disabled the addon for this problem. hope ticktackk do something.
