### ISSUE TITLE
Bump content time work?

### ISSUE THREAD

**Issue by smallersign** [ticktackk/ChangeContentOwnerForXF2#74]
**Bump content time by specific hours, minutes or seconds.** What is this feature?

Cant understand really.

**Comment by ticktackk** [comment]
It is just the change content date feature.

**Comment by smallersign** [comment]
It's not working.  I have set time interval, but nothing changed.
[https://i.postimg.cc/0QDBttSp/screenshot-1649.png](url)

**Comment by smallersign** [comment]
This is bug

**Comment by ticktackk** [comment]
This issue was originally created to ask a question which has been answered. You must now create a new issue if you have any bug report.
